# Versão do docker-compose
version: '3.8'

services:
  mestre:
    build:
      # Define o contexto de build como o diretório raiz (onde este arquivo está)
      context: .
      # Especifica o caminho para o Dockerfile do mestre, a partir do contexto
      dockerfile: mestre/Dockerfile
    ports:
      # Expõe a porta 8080 do container na porta 8080 da sua máquina
      - "8080:8080"
    # Garante que os escravos iniciem antes do mestre
    depends_on:
      - escravo1-letras
      - escravo2-numeros

  escravo1-letras:
    build:
      context: .
      dockerfile: escravo1-letras/Dockerfile
    # A porta 8081 só precisa ser acessível pelos outros containers,
    # não precisa expor para a máquina host.

  escravo2-numeros:
    build:
      context: .
      dockerfile: escravo2-numeros/Dockerfile
    # A porta 8082 também é apenas para comunicação interna.
