
version: '3.8'

services:
  mestre:
    build:
      
      context: .
      dockerfile: mestre/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - escravo1-letras
      - escravo2-numeros

  escravo1-letras:
    build:
      context: .
      dockerfile: escravo1-letras/Dockerfile

  escravo2-numeros:
    build:
      context: .
      dockerfile: escravo2-numeros/Dockerfile
   
